function [...
    intl_tri_is_vbl, ...
    intl_edg_srfc_inds, ...
    intl_vrtx_inds,...
    srfc_pnt_is_vbl_intl]...
    ...
    = intl_srfc_data_pnt(...
    ...
    srfc_crdnts, ...
    vrtx_crdnts, ...
    tri_vrtx_inds, ...
    edg_vrtx_inds, ...
    srfc_pnt_is_vbl_intl, ...
    intl_edg_lngth, ...
    cnstrnt_rds, ...
    srch_rds1, ...
    srch_rds2, ...
    emprcl_drctn_crrltn_eval_bias, ...
    nnz_egnvals, ...
    use_sprs_algrthm, ...
    non_adj_tri_dist_tol, ...
    non_adj_tri_dist_tol_ovrlap, ...
    nrbyVrtxDstncTol, ...
    max_tries)

intl_edg_srfc_inds    = [];
intl_vrtx_inds        = [];
fnd_vbl_intl_srfc_pnt = false;
intl_tri_is_vbl       = false(1, 2);

num_tris = 0;
while ~fnd_vbl_intl_srfc_pnt && num_tris <= max_tries
    
    num_tris = num_tris + 1;
    
    [min_dstnc, min_indx] = ...
        min_inter_crdnt_set_dstncs(srfc_crdnts, vrtx_crdnts);
    
    %low priority optimization opportunity
    min_dstnc(~srfc_pnt_is_vbl_intl) = -Inf;
    
    [max_min_dstnc, intl_srfc_pnt_indx] = max(min_dstnc);
    %intl_srfc_pnt_indx = min_indx(max_min_indx);
    
    fnd_vbl_intl_srfc_pnt = any(srfc_pnt_is_vbl_intl);
    
    if fnd_vbl_intl_srfc_pnt
        
        [intl_edg_srfc_inds, intl_vrtx_inds] = gen_init_tris2(...
            srfc_crdnts, ...
            intl_srfc_pnt_indx, ...
            intl_edg_lngth, ...
            cnstrnt_rds, ...
            srch_rds1, ...
            srch_rds2, ...
            emprcl_drctn_crrltn_eval_bias, ...
            use_sprs_algrthm, ...
            nnz_egnvals);
        
        if isempty(intl_edg_srfc_inds)
            %could not generate initial triangles from the initial surface
            %point
            srfc_pnt_is_vbl_intl(intl_srfc_pnt_indx) = false;
            fnd_vbl_intl_srfc_pnt = false;
            
        else
            %check if each initial triangle is viable
            [intl_tri_is_vbl] = intl_tris_are_vbl(...
                tri_vrtx_inds, ...
                edg_vrtx_inds, ...
                vrtx_crdnts, ...
                intl_edg_srfc_inds, ...
                intl_vrtx_inds, ...
                srfc_crdnts,...
                nrbyVrtxDstncTol, ...
                non_adj_tri_dist_tol, ...
                non_adj_tri_dist_tol_ovrlap);
            
            fnd_vbl_intl_srfc_pnt = any(intl_tri_is_vbl);
            
            if ~fnd_vbl_intl_srfc_pnt
                %neither of the initial triangles was viable
                srfc_pnt_is_vbl_intl(intl_srfc_pnt_indx) = false;
                
            end
            
        end
        
    end
    
end
