%wrapper for
%plot_hndls = struct(...
%    'surf_pts_hndl', [], ...
%    'tris_hndl', [], ...
%    'front_hndls', [], ...
%    'actv_edge_hndl', [], ...
%    'actv_edge_intr_hndl', [], ...
%    'cand_vert_and_surf_hndl', []);
function plot_hndls = new_plot_hndls()

plot_hndls = struct(...
    'surf_pts_hndl', [], ...
    'tris_hndl', [], ...
    'front_hndls', [], ...
    'actv_edge_hndl', [], ...
    'actv_edge_intr_hndl', [], ...
    'cand_vert_and_surf_hndl', [], ...
    'x0_hndl', []);

end