%wrapper for
%cndt_vrtx_info = struct(...
%    'is_exstng_vrtx', false, ...
%    'is_frnt_edg_vrtx', false, ...
%    'is_actv_edg_vrtx', false, ...
%    'vrtx_ind', 0, ...
%    'srfc_pt_ind', 0, ...
%    'crds', zeros(crdnt_dmnsn,1));
function cndt_vrtx_info = new_cndt_vrtx_info(crdnt_dmnsn)

cndt_vrtx_info = struct(...
    'is_exstng_vrtx', false, ...
    'is_frnt_edg_vrtx', false, ...
    'is_actv_edg_vrtx', false, ...
    'vrtx_ind', 0, ...
    'srfc_pt_ind', 0, ...
    'crds', zeros(crdnt_dmnsn,1));

end
