function SNPCA_params = new_SNPCA_params()

SNPCA_params = struct(...
    'chrctrstc_lngth', NaN, ...
    'cnstrnt_rad_fac', NaN, ...
    'new_tri_max_edg_lngth', NaN, ...
    'srch_rad_fac1', NaN, ...
    'srch_rad_fac2', NaN, ...
    'intl_pt_ind', NaN, ...
    'prfrd_cnstrnt_rds', NaN, ...
    'prfrd_cnstrnt_rds_wght', NaN, ...
    'non_adj_tri_dist_tol', NaN, ...
    'non_adj_tri_ovrlap_dist_tol', -Inf, ...
    'cand_vert_max_nudge_dist', NaN, ...
    'adj_vert_max_nudge_dist', NaN, ...    
    'nrby_vrtx_dstnc_tol', Inf, ...
    'emprcl_drctn_crrltn_eval_bias', NaN, ....
    'nnz_egnvals', NaN, ...
    'emprcl_drctn_egn_sprs_algrthm', false, ...
    'plot_frqncy', NaN, ...
    'max_num_restarts', NaN, ...
    'rtn_mtrx', NaN, ...
    'save_data', false, ... 
    'path_saved_data', ['interleaved_data' filesep()], ...
    'MAX_NUM_VRTCS', 2048, ...
    'INTL_EDG_FIFO_LNGTH', 1024, ...
    'INTL_NUM_VRTXS', 1024, ...
    'INTL_NUM_EDGS', 0, ...
    'INTL_NUM_TRIS', 0);

SNPCA_params.INTL_NUM_EDGS = 4*SNPCA_params.INTL_NUM_VRTXS;
SNPCA_params.INTL_NUM_TRIS = 2*SNPCA_params.INTL_NUM_VRTXS;