%wrapper for:
%error_struct = struct(...
%    'self_collision', false, ...
%    'err_id', '', ...
%    'adj_tri_collision_inds', [], ...
%    'non_adj_tri_collision_inds', []);

function error_struct = new_error_struct()

error_struct = struct(...
    'self_collision', false, ...
    'err_id', '', ...
    'adj_tri_collision_inds', [], ...
    'non_adj_tri_collision_inds', []);

end