function vrtx_inds = non_shrd_adj_frnt_edg_vrtx_inds(...
    actv_edg_ind, frnt_edg_inds, edg_vrtx_inds)

adjcnt_frnt_edg_inds = adjcnt_frnt_edgs(...
    actv_edg_ind, frnt_edg_inds, edg_vrtx_inds);

adjcnt_frnt_edg_vtx_inds = ...
    edg_vrtx_inds(...
    union(adjcnt_frnt_edg_inds{1}, adjcnt_frnt_edg_inds{2}), 1:2);

adjcnt_frnt_edg_vtx_inds = unique(adjcnt_frnt_edg_vtx_inds(:));

actv_vrtx_inds = edg_vrtx_inds(actv_edg_ind, 1:2);

vrtx_blngs_to_actv_edg = ...
    actv_vrtx_inds(1) == adjcnt_frnt_edg_vtx_inds ...
    | actv_vrtx_inds(2) == adjcnt_frnt_edg_vtx_inds;

vrtx_inds = ...
    adjcnt_frnt_edg_vtx_inds(~vrtx_blngs_to_actv_edg);

end