function [triVrtxInds, edgVrtxInds, numTris, numEdgs] ...
    = sew_seams_decomp4(...
    srfcCrdnts, ...
    vrtx_ind_to_srfc_pt_ind, ...
    vrtxCrdnts, ...
    triVrtxInds, ...
    edgVrtxInds, ...
    numVrtxs, ...
    numTris, ...
    numEdgs, ...
    invbl_edg_inds, ...
    numInvblEdgInds, ...
    P_dmnt_egnvctrs, ...
    P_dmnt_egnvals, ...
    emprcl_drctn_crrltn_eval_bias, ...
    nnzEvals, ...
    emprcl_drctn_egn_sprs_algrthm , ...
    eigsOpts, ...
    new_tri_max_edg_lngth, ...
    non_adj_tri_dist_tol, ...
    non_adj_tri_ovrlap_dist_tol, ...
    rtn_mtrx, ...
    plot_hndls, ...
    plot_frqncy)


vrtx_crdnts_3D = rtn_mtrx(:,1:3)'*vrtxCrdnts(:, 1:numVrtxs);

dmnsn = size(vrtxCrdnts, 1);

dstnc_objctvs_decomp = cell(1,2);

edg_is_frnt       = ...
    edge_blngs_to_xctly_one_tri(...
    edgVrtxInds(1:numEdgs, :), ...
    triVrtxInds(1:numTris, :));
frnt_edg_inds     = find(edg_is_frnt);
VblFrntEdgInds    = setdiff(frnt_edg_inds, invbl_edg_inds);
numViableFrntEdgs = numel(VblFrntEdgInds);

while numViableFrntEdgs > 0
    
    tic
    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %generate sequence of front edges as visited in a breadth first search        
    frnt_edg_vrtx_inds = edgVrtxInds(edg_is_frnt, 1:2);
    adjcncy_lst = edge_adjacency_list(frnt_edg_vrtx_inds);
    edg_q = breadth_first_search(adjcncy_lst, 1);
    edg_q = frnt_edg_inds(edg_q);
    edg_fifo_stack = edg_q;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %srch_box_edg_lngths    = zeros(dmnsn, 1);
    %srch_box_edg_lngths(:) = 1.5*new_tri_max_edg_lngth;
    %num_to_find = 50;
    
    [triVrtxInds, numTris, ...
        edgVrtxInds, numEdgs, ...
        invbl_edg_inds, numInvblEdgInds] ...
        = ...
        new_tris_frm_frnt_edg(...
        srfcCrdnts, ...
        vrtx_ind_to_srfc_pt_ind, ...
        vrtxCrdnts(:, 1:numVrtxs), ...
        edg_fifo_stack, ...
        triVrtxInds, ...
        edgVrtxInds, ...
        numTris, ...
        numEdgs, ...
        P_dmnt_egnvctrs, ...
        P_dmnt_egnvals, ...
        emprcl_drctn_crrltn_eval_bias, ...
        nnzEvals, ...
        emprcl_drctn_egn_sprs_algrthm, ...
        eigsOpts, ...
        invbl_edg_inds, ...
        numInvblEdgInds, ...
        Inf, ...%non_adj_tri_dist_tol, ...
        non_adj_tri_ovrlap_dist_tol, ...
        new_tri_max_edg_lngth, ...
        plot_hndls, ...
        plot_frqncy, ...
        vrtx_crdnts_3D);
    
    edg_is_frnt       = edge_blngs_to_xctly_one_tri(...
        edgVrtxInds(1:numEdgs, :), ...
        triVrtxInds(1:numTris, :));
    frnt_edg_inds     = find(edg_is_frnt);
    VblFrntEdgInds    = setdiff(frnt_edg_inds, invbl_edg_inds);
    numViableFrntEdgs = numel(VblFrntEdgInds);
    
    toc
    
    %save ruh_roh;
    
end
