function tri_contains_edg = tri_contains_edg(...
    edg_vrtx1, edg_vrtx2, tri_vrtx_inds)

tri_contains_edg = ...
    (edg_vrtx1 == tri_vrtx_inds(:,1) ...
    & ...
    (edg_vrtx2 == tri_vrtx_inds(:,2) | edg_vrtx2 == tri_vrtx_inds(:,3)))...
    | ...
    (edg_vrtx1 == tri_vrtx_inds(:,2) ...
    & ...
    (edg_vrtx2 == tri_vrtx_inds(:,1) | edg_vrtx2 == tri_vrtx_inds(:,3)))...
    | ...
    (edg_vrtx1 == tri_vrtx_inds(:,3) ...
    & ...
    (edg_vrtx2 == tri_vrtx_inds(:,1) | edg_vrtx2 == tri_vrtx_inds(:,2)));