function [] = update_tri_surf(tri_surf_hndl, tris,...
                              tri_crds_x, tri_crds_y, tri_crds_z)

%updates the triangle surface plot with handle tri_surf_hndl
%the connectivity info is stored in tris
%the triangle vertex info is stored in tri_crds_x, etc.

% set(tri_surf_hndl, ...
%     'Faces', tris, ...
%     'Vertices', [tri_crds_x(:) tri_crds_y(:) tri_crds_z(:)]);

%colormap(bone);

set(tri_surf_hndl, ...
    'XData', tri_crds_x, ...
    'YData', tri_crds_y, ...
    'ZData', tri_crds_z, ...
    'Faces', tris);



%set(tri_surf_hndl, ...
%    'Faces', tris, ...
%    'XData', tri_crds_x, ...
%    'YData', tri_crds_y, ...
%    'ZData', tri_crds_z, ...
%    'Vertices', [tri_crds_x(:) tri_crds_y(:) tri_crds_z(:)]);
% set(tri_surf_hndl, 'XData', tri_crds_x(tris).');
% set(tri_surf_hndl, 'YData', tri_crds_y(tris).');
% set(tri_surf_hndl, 'ZData', tri_crds_z(tris).');
